name: 'PR Channel Slackbot'
description: 'A GitHub Action to check slack channels for PRs that are still open'
branding:
  icon: 'git-pull-request'
  color: 'white'

inputs:
  slack-token:
    description: 'Slack API token'
    required: true
  github-token:
    description: 'GitHub API token'
    required: true
  config-file:
    description: 'Path to JSON Config file'
    required: true

runs:
  using: node20
  main: dist/index.mjs